"""initial

Revision ID: c2fc9d51de02
Revises:
Create Date: 2026-05-21 13:31:53.547831
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c2fc9d51de02"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plant_code", sa.String(length=16), nullable=False),
        sa.Column("verify_hash", sa.String(length=128), nullable=False),
        sa.Column("is_paired", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_devices_plant_code"), "devices", ["plant_code"], unique=True
    )
    op.create_table(
        "exp_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quality_level", sa.String(length=20), nullable=False),
        sa.Column("exp_delta", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quality_level"),
    )
    op.create_table(
        "plant_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("soil_moisture_min", sa.Float(), nullable=False),
        sa.Column("soil_moisture_max", sa.Float(), nullable=False),
        sa.Column("light_min", sa.Float(), nullable=False),
        sa.Column("light_max", sa.Float(), nullable=False),
        sa.Column("temperature_min", sa.Float(), nullable=False),
        sa.Column("temperature_max", sa.Float(), nullable=False),
        sa.Column("humidity_min", sa.Float(), nullable=False),
        sa.Column("humidity_max", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "rank_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("min_exp", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("order"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("google_id", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.create_table(
        "plants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("plant_type_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("total_exp", sa.Float(), nullable=False),
        sa.Column("current_rank_id", sa.UUID(), nullable=False),
        sa.Column("last_exp_reward_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_rank_id"],
            ["rank_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plant_type_id"],
            ["plant_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "breakthrough_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("from_rank", sa.String(length=50), nullable=False),
        sa.Column("to_rank", sa.String(length=50), nullable=False),
        sa.Column("exp_at_breakthrough", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_breakthrough_events_plant_id"),
        "breakthrough_events",
        ["plant_id"],
        unique=False,
    )
    op.create_table(
        "exp_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("overall_quality", sa.String(length=20), nullable=False),
        sa.Column("total_exp_after", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exp_logs_plant_id"), "exp_logs", ["plant_id"], unique=False
    )
    op.create_table(
        "sensor_readings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("sensor_key", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("quality", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sensor_readings_created_at"),
        "sensor_readings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_sensor_readings_plant_created",
        "sensor_readings",
        ["plant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_sensor_readings_plant_key_created",
        "sensor_readings",
        ["plant_id", "sensor_key", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sensor_readings_plant_key_created", table_name="sensor_readings")
    op.drop_index("ix_sensor_readings_plant_created", table_name="sensor_readings")
    op.drop_index(op.f("ix_sensor_readings_created_at"), table_name="sensor_readings")
    op.drop_table("sensor_readings")
    op.drop_index(op.f("ix_exp_logs_plant_id"), table_name="exp_logs")
    op.drop_table("exp_logs")
    op.drop_index(
        op.f("ix_breakthrough_events_plant_id"), table_name="breakthrough_events"
    )
    op.drop_table("breakthrough_events")
    op.drop_table("plants")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("rank_configs")
    op.drop_table("plant_types")
    op.drop_table("exp_configs")
    op.drop_index(op.f("ix_devices_plant_code"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
